config/routes.rb
Rails.application.routes.draw do

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get 'chat/:user_id'=>"chats#chat", as: :chat

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create]
  end
  resources :book_comments, only: [:destroy]

  resources :users, only: [:index,:show,:edit,:update] do
    member do
      get 'followers'
      get 'followings'
    end
    resource :relationships, only: [:create, :destroy]
    resources :chats, only: [:create]
    get "search", to: "users#search"
  end
  
  resources :groups do    #ここ！
    get "join" => "groups#join"
    get '/new_event' => 'groups#notice_event'
    post '/new_event' => 'groups#create_event_mail'
    get '/confirm_mail' => 'groups#confirm_mail'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users

  validates :name, presence: true
  validates :introduction, presence: true
  has_one_attached :profile_image
  
  def get_profile_image(size)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/png')
    end
    profile_image.variant(resize: size).processed
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def index
    @book = Book.new
    @groups = Group.all
  end

  def show
    @book = Book.new
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end
  
  def join #追記！
    @group = Group.find(params[:group_id])
    @group.users << current_user
    redirect_to  groups_path
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    #追記しています！！！
    @group.users << current_user
    if @group.save
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to groups_path
    else
      render "edit"
    end
  end
  
  def destroy
    @group = Group.find(params[:id])
    #current_userは、@group.usersから消されるという記述。
    @group.users.delete(current_user)
    redirect_to groups_path
  end
  
  def notice_event
  end

  def create_event_mail
    @group_member = Group.find(params[:group_id]).group_users

    @group_member.each do |member|
      EventMailer.with(user_id: member.user.id, title: params[:title], content: params[:content]).notice_email.deliver_later
    end

    render :confirm_mail
  end

  def confirm_mail
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @group = Group.find(params[:id])
    unless @group.owner_id == current_user.id
      redirect_to groups_path
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with model: group, local: true do |f| %>
  <div class="form-group">
    <%= f.label :グループ名 %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :紹介文 %>
    <%= f.text_area :introduction, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :グループ画像 %>
    <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-info' %>
  </div>
<% end %>

app/views/groups/confirm_mail.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <h1>送信が完了しました</h1>

      <p>内容は以下の通りです。</p>

      <h2>[タイトル]</h2>
      <p><%= params[:title] %></p>

      <h2>[本文]</h2>
      <p><%= params[:content] %></p>
    </div>
  </div>
</div>

app/views/groups/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>Editing Group</h3>
      <%= render 'form', group: @group %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class='col-md-8 offset-md-1'>
  <h2>Groups</h2>
  <table class='table table-hover table-inverse'>
    <thead>
      <tr>
        <th></th>
        <th>グループ名</th>
        <th>紹介文</th>
        <th>メンバー数</th>
      </tr>
    </thead>
    <tbody>
      <% @groups.each do |group| %>
        <tr>
          <td><%= image_tag group.get_profile_image("100x100") %></td>
          <td><%= link_to group.name, group_path(group) %></td>
          <td><%= group.introduction %></td>
          <td><%= group.users.count %></td>
          <td>
            <% if group.owner_id == current_user.id %>
              <%= link_to 'Edit', edit_group_path(group), class: "btn btn-sm btn-success" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/groups/new.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>Create Group</h3>
        <%= render 'form', group: @group %>
    </div>
  </div>
</div>

app/views/groups/new_mail.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Event Mail</h2>
      <%= form_with url: group_send_mail_path(@group),method: :get, local: true do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :mail_title,class:'form-control'%>
        </div>
        <div class="form-group">
          <%=f.label:content %>
          <%= f.text_area :mail_content,class:'form-control' %>
        </div>
        <div>
          <%= f.submit'送信' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/notice_event.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 mx-auto">
      <%= form_with url: group_new_event_path(params[:group_id]), method: :post do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control book_title' %>
        </div>
        <div class="form-group">
          <%= f.label :content %>
          <%= f.text_area :content, class: 'form-control book_body' %>
        </div>
        <div class="form-group">
          <%= f.submit "送信", class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/send_mail.html.erb
<div class="container">
  <h3 class="margin_top text-center">送信が完了しました</h3>
  <div class="main_width">
  <div class="margin_top">内容は以下の通りです。</div>
    <div class="small_margin_top">
      [タイトル]<p class="font-weight-bold"> <%= @mail_title %></p>
    </div>
    <div>
      [本文]<p class="font-weight-bold"> <%= safe_join(@mail_content.split("\n"),tag(:br)) %></p>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Group Detail</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= image_tag @group.get_profile_image("100x100") %></td>
            <td><%= @group.name %></td>
            <td><%= @group.introduction %></td>
            <td>
              <% @group.users.each do |member| %>
                <%= member.name %><br>
              <% end %>
            </td>
            <td>
              <% if @group.owner_id == current_user.id %>
                <%= link_to 'Edit', edit_group_path(@group), class: "btn btn-sm btn-success" %>
                <%= link_to 'Notice an Event', group_new_event_path(@group.id), class: "btn btn-sm btn-primary" %>
              <% elsif @group.users.include?(current_user) %>
                <%= link_to 'Leave this group', group_path(@group), method: :delete, class: "btn btn-sm btn-danger" %>
              <% else %>
                <%= link_to 'Join this group', group_join_path(@group), class: "btn btn-sm btn-success" %>
              <% end %>
            </td>
          </tr>
        <tbody>
      </table>
    </div>
  </div>
</div>