config/routes.rb
Rails.application.routes.draw do

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get 'chat/:user_id'=>"chats#chat", as: :chat

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create]
  end
  resources :book_comments, only: [:destroy]

  resources :users, only: [:index,:show,:edit,:update] do
    member do
      get 'followers'
      get 'followings'
    end
    resource :relationships, only: [:create, :destroy]
    resources :chats, only: [:create]
    get "search", to: "users#search"
  end
  
  resources :groups do    #ここ！
    get "join" => "groups#join"
    get '/new_event' => 'groups#notice_event'
    post '/new_event' => 'groups#create_event_mail'
    get '/confirm_mail' => 'groups#confirm_mail'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :book_comments
  has_many :favorites, dependent: :destroy
  has_many :group_users   #ここ！
  has_many :groups, through: :group_users
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  # フォロワー
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'followee_id'
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # フォローしている人
  has_many :relationships, class_name: 'Relationship', foreign_key: "follower_id"
  has_many :followings, through: :relationships, source: :followee

  def get_profile_image(size)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/png')
    end
    profile_image.variant(resize: size).processed
  end
  
  def following?(user)
    followings.include?(user)
  end
  
  def follow(another_user)
    unless self == another_user
      self.relationships.find_or_create_by(followee_id: another_user.id)
    end
  end

  def unfollow(another_user)
    unless self == another_user
      relationship = self.relationships.find_by(followee_id: another_user.id)
      relationship.destroy if relationship
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end
  
  def followings
    @user = User.find(params[:id])
  end

  def followers
    @user = User.find(params[:id])
  end
  
  def search
    @user = User.find(params[:user_id])
    @books = @user.books 
    @book = Book.new
    if params[:created_at] == ""
      @search_book = "日付を選択してください"#①
    else
      create_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE ? ', "#{create_at}%"]).count#②
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image("50x50") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image("100x100") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>フォロー中</th>
    <th>
      <%= link_to followings_user_path(user) do %>
        <%= user.followings.count %>人
      <% end %>
    </th>
  </tr>
  <tr>
    <th>フォロワー</th>
    <th>
      <%= link_to followers_user_path(user) do %>
        <%= user.followers.count %>人
      <% end %>
    </th>
  </tr>
  <% unless current_user == user %>
    <tr>
      <th>
        <% if current_user.following?(user) %>
          <% link_to "フォロー外す", user_relationships_path(user), method: :delete, class:"btn btn-default" %>
        <% else %>
          <% link_to "フォローする", user_relationships_path(user), method: :post, class:"btn btn-primary" %>
        <% end %>
      </th>
    </tr>
  <% end %>
</table>

<div class='row'>
  <% if current_user == user %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% elsif current_user.following?(user) %>
    <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-info" %>
    <% if current_user.followed?(user) %>
      <%= link_to "chatを始める", chat_path(user.id) %>
    <% end %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
  <% end %>
</div>

app/views/users/_search.html.erb
<h4>検索結果</h4>
<table class='table table-bordered'>
  <thead>
    <tr> 
      <th>投稿数</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= search_book %></td>
    </tr>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <div><%=link_to "グループを作成する",new_group_path %> | <%=link_to "グループ一覧",groups_path %></div>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/search.js.erb
$("#search_result").html("<%= j(render 'search', search_book: @search_book) %>");

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
      <h2>投稿数の前日比・前週比</h2>
      <table class='table'>
        <thead>
          <tr>
            <th>今日の投稿数</th>
            <th>前日の投稿数</th>
            <th>前日比</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @today_book.count %></td>
            <td><%= @yesterday_book.count %></td>
            <td>
              <% if @yesterday_book.count == 0 %>
                前日の投稿はありません
              <% else %>
                <% @the_day_before =   @today_book.count / @yesterday_book.count.to_f  %>
                <%= (@the_day_before * 100).round %>%
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>

      <table class='table'>
        <thead>
          <tr>
            <th>今週の投稿数</th>
            <th>前週の投稿数</th>
            <th>前週比</th>
          </tr>
        </thead>
        <tbody>
          <tr>
           　<td><%= @this_week_book.count %></td>
             <td><%= @last_week_book.count %></td>
             <td>
              <% if @last_week_book.count == 0 %>
                前週の投稿はありません
              <% else %>
                <% @the_week_before =   @this_week_book.count / @last_week_book.count.to_f  %>
                %= (@the_week_before * 100).round %>%
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>